let currentDate=new Date().toISOString().slice(0,10);if(!SCHEDULE[currentDate])currentDate='2026-08-12';let currentReminderId=null;let selectedMin=10;
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function dayLabel(d){const x=new Date(d+'T00:00:00');return `${x.getMonth()+1}月${x.getDate()}日 周${'日一二三四五六'[x.getDay()]}`}
function render(){const tasks=SCHEDULE[currentDate]||[];const done=tasks.filter(t=>isDone(t.id)).length;const rate=tasks.length?Math.round(done/tasks.length*100):0;document.getElementById('dateTitle').textContent=dayLabel(currentDate);document.getElementById('daySub').textContent=`第 ${DATES.indexOf(currentDate)+1} 天 / ${DATES.length} 天`;document.getElementById('modeText').textContent=['2026-08-12','2026-08-13'].includes(currentDate)?'🌿 轻松模式 · 核心任务优先':currentDate==='2026-08-15'||currentDate==='2026-08-16'?'💪 周末加量 · 含顺延任务':currentDate==='2026-08-23'?'🎯 考试日':'正常冲刺';document.getElementById('dayDone').textContent=done;document.getElementById('dayTotal').textContent=tasks.length;document.getElementById('dayRate').textContent=rate+'%';document.getElementById('dayBar').style.width=rate+'%';document.getElementById('tasks').innerHTML=tasks.map(t=>{const d=isDone(t.id),r=reminder(t.id);return `<article class="task ${d?'done':''}"><button class="check" onclick="event.stopPropagation();complete('${t.id}')">${d?'✓':''}</button><div class="task-main" onclick="complete('${t.id}')"><div class="meta"><span class="tag" style="background:${MODULE_COLOR[t.module]||'#64748b'}">${t.module}</span><span class="time">${t.start}</span><span class="time">${t.duration}</span>${t.moved?'<span class="tag" style="background:#f59e0b">顺延</span>':''}</div><div class="task-text">${t.task}</div></div><div class="task-actions"><button class="bell" onclick="event.stopPropagation();openReminder('${t.id}')">${r?'🔔':'🔕'}</button></div></article>`}).join('');renderTotal()}
function complete(id){toggleDone(id);render();toast(isDone(id)?'已完成 ✓':'已取消完成')}
function renderTotal(){let total=0,done=0;for(const d of DATES){for(const t of SCHEDULE[d]){total++;if(isDone(t.id))done++}}const p=total?Math.round(done/total*100):0;document.getElementById('totalPct').textContent=p+'%'}
function renderStats(){const names={listening:'听力',reading:'阅读',tests:'真题/剑雅',speaking:'口语',writing:'写作',vocab:'词汇',review:'错题复盘'};const s=statistics();document.getElementById('statCards').innerHTML=Object.entries(names).map(([k,n])=>`<div class="panel"><b>${n}</b><div style="font-size:22px;color:#0284c7;margin-top:5px">${s[k][0]} / ${s[k][1]}</div><div class="muted">已完成 / 计划任务</div></div>`).join('');document.getElementById('overallBars').innerHTML=Object.entries(names).map(([k,n])=>{const [a,b]=s[k],p=b?Math.round(a/b*100):0;return `<div class="metric"><div class="metric-top"><span>${n}</span><b>${p}%</b></div><div class="metric-bar"><i style="width:${p}%"></i></div></div>`}).join('')}
function renderDates(){document.getElementById('datePicker').innerHTML=DATES.map(d=>`<button onclick="currentDate='${d}';switchTab('today');render()"><b>${dayLabel(d)}</b><br><span class="muted">${SCHEDULE[d].length} 项任务</span></button>`).join('')}
function switchTab(tab){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));todayView.hidden=tab!=='today';statsView.hidden=tab!=='stats';planView.hidden=tab!=='plan';if(tab==='stats')renderStats();if(tab==='plan')renderDates()}
function openReminder(id){currentReminderId=id;document.getElementById('reminderModal').hidden=false;const t=Object.values(SCHEDULE).flat().find(x=>x.id===id);document.getElementById('reminderLabel').textContent=t?`${t.module} · ${t.start} · ${t.task}`:'';document.querySelectorAll('.reminder-grid button').forEach(b=>b.classList.toggle('selected',false));selectedMin=10}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.getElementById('notifyBtn').onclick=requestNotifications;document.getElementById('installBtn').onclick=installApp;document.getElementById('weekendBtn').onclick=()=>{currentDate='2026-08-15';switchTab('today');render()};document.getElementById('closeReminder').onclick=()=>document.getElementById('reminderModal').hidden=true;document.querySelectorAll('.reminder-grid button').forEach(b=>b.onclick=()=>{selectedMin=+b.dataset.min;document.querySelectorAll('.reminder-grid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.getElementById('saveReminder').onclick=()=>{const t=Object.values(SCHEDULE).flat().find(x=>x.id===currentReminderId);if(!t)return;const v=document.getElementById('customTime').value;let d=new Date(currentDate+'T'+(v||t.start)+':00');if(!v)d=new Date(d.getTime()-selectedMin*60000);scheduleReminder(currentReminderId,d.toISOString());document.getElementById('reminderModal').hidden=true;render()};document.getElementById('clearReminder').onclick=()=>{clearReminder(currentReminderId);document.getElementById('reminderModal').hidden=true;render()};render();renderTotal();