/* KENZO in-browser editor: text + local media replacement, saved on this device. */
(function(){
  const EDIT_KEY='kenzo_editor_text_v1';
  const DB_NAME='kenzo_editor_media_v1';
  const STORE='media';
  let edit=false, panel=null, textMap=JSON.parse(localStorage.getItem(EDIT_KEY)||'{}');
  const style=document.createElement('style');
  style.textContent=`
  .ke-btn{position:fixed;z-index:120;right:12px;top:calc(10px + env(safe-area-inset-top));border:1px solid #333;background:#111;color:#fff;border-radius:999px;padding:9px 12px;font-size:11px;font-weight:700;letter-spacing:.06em;box-shadow:0 8px 25px #0005}.ke-btn.on{background:#ff2442;border-color:#ff2442}.ke-editing [contenteditable=true]{outline:1px dashed #ff2442!important;outline-offset:3px;border-radius:4px;cursor:text}.ke-editing .mediaCard img,.ke-editing .mediaCard video,.ke-editing .refCard img,.ke-editing .refCard video,.ke-editing .caseMini img,.ke-editing .caseMini video{outline:2px dashed #ff2442;outline-offset:-4px;cursor:pointer}.ke-panel{position:fixed;z-index:130;inset:0;background:#0009;display:none;align-items:flex-end;justify-content:center}.ke-panel.show{display:flex}.ke-sheet{width:min(448px,100%);max-height:86dvh;overflow:auto;background:#fff;color:#111;border-radius:24px 24px 0 0;padding:14px 14px calc(22px + env(safe-area-inset-bottom))}.ke-head{display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#fff;padding:4px 0 12px;z-index:2}.ke-head h3{margin:0;font-size:18px}.ke-close{border:0;background:#f1f1f1;border-radius:50%;width:34px;height:34px;font-size:20px}.ke-note{font-size:11px;line-height:1.65;color:#777;margin-bottom:12px}.ke-grid{display:grid;gap:9px}.ke-row{border:1px solid #e8e8e8;border-radius:15px;padding:11px;display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.ke-row b{display:block;font-size:12px}.ke-row small{display:block;color:#999;margin-top:4px;font-size:10px}.ke-pick{border:1px solid #111;background:#111;color:#fff;border-radius:999px;padding:8px 10px;font-size:10px}.ke-tools{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.ke-tools button{height:42px;border-radius:12px;border:1px solid #ddd;background:#fff;font-size:11px}.ke-tools .danger{color:#c22}.ke-toast{position:fixed;z-index:160;left:50%;bottom:90px;transform:translateX(-50%) translateY(12px);background:#111;color:#fff;padding:9px 12px;border-radius:999px;font-size:11px;opacity:0;pointer-events:none;transition:.2s}.ke-toast.show{opacity:1;transform:translateX(-50%) translateY(0)}
  `; document.head.appendChild(style);
  const btn=document.createElement('button'); btn.className='ke-btn'; btn.textContent='EDIT'; document.body.appendChild(btn);
  const toast=document.createElement('div'); toast.className='ke-toast'; document.body.appendChild(toast);
  const slots=[
    ['case-0','案例 01 · 发票 GIF','GIF / 图片 / 视频'],['case-1','案例 02 · 拼贴 GIF','GIF / 图片 / 视频'],['case-2','案例 03 · 鲜花 GIF','GIF / 图片 / 视频'],['image-0','图文参考 · ROMI STUDIO','图片'],
    ['ref-0','参考视频 01','视频'],['ref-1','参考视频 02','视频'],['ref-2','参考视频 03','视频'],['ref-3','参考视频 04','视频'],['ref-4','参考视频 05','视频'],['ref-5','参考视频 06','视频'],['ref-6','参考视频 07','视频'],['ref-7','参考视频 08','视频']
  ];
  function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1300)}
  function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function dbPut(k,v){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  async function dbGet(k){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function dbClear(){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  function keyForText(el,idx){let w='xhs',c=0,t=0;try{w=S.world;c=S.chapter;t=S.tab||0}catch(e){} return `${w}:${c}:${t}:${el.tagName}.${el.className||''}:${idx}`}
  const textSel='.note h2,.lead,.row b,.row p,.dir h3,.dir p,.platformBox b,.platformBox p,.quote,.check b,.check p,.sheetLead,.caption h2,.caption p,.mediaText b,.mediaText p,.refText b,.refText small,.slab,.tags';
  function applyText(){const els=[...document.querySelectorAll(textSel)];els.forEach((el,i)=>{const k=keyForText(el,i);el.dataset.ke=k;if(textMap[k]!=null && !el.dataset.keApplied){el.innerText=textMap[k];el.dataset.keApplied='1'}el.contentEditable=edit?'true':'false';el.spellcheck=false})}
  function logicalKeyFromCard(card){if(!card)return null;const kind=card.dataset.kind||'';const v=card.dataset.v||'0'; if(kind==='case')return `case-${v}`; if(kind==='ref')return `ref-${v}`; if(kind==='image')return 'image-0'; return null}
  function replaceNodeMedia(node,blob){const url=URL.createObjectURL(blob);let n=node;const isVideo=blob.type.startsWith('video/');const shouldVideo=isVideo; if(shouldVideo && node.tagName!=='VIDEO'){const v=document.createElement('video');v.autoplay=true;v.muted=true;v.loop=true;v.playsInline=true;v.controls=false;v.className=node.className;node.replaceWith(v);n=v}else if(!shouldVideo && node.tagName!=='IMG'){const im=document.createElement('img');im.className=node.className;node.replaceWith(im);n=im}n.src=url;if(n.tagName==='VIDEO'){n.load();n.play().catch(()=>{})}}
  async function applyMedia(){const cards=[...document.querySelectorAll('[data-a="media"]')];for(const card of cards){const k=logicalKeyFromCard(card);if(!k)continue;const blob=await dbGet(k).catch(()=>null);if(!blob)continue;const node=card.querySelector('img,video');if(node)replaceNodeMedia(node,blob)}
    // hero mini cases
    const minis=[...document.querySelectorAll('.caseMini img,.caseMini video')];for(let i=0;i<Math.min(3,minis.length);i++){const b=await dbGet(`case-${i}`).catch(()=>null);if(b)replaceNodeMedia(minis[i],b)}
  }
  function refresh(){document.body.classList.toggle('ke-editing',edit);btn.textContent=edit?'DONE':'EDIT';btn.classList.toggle('on',edit);applyText();applyMedia()}
  document.addEventListener('input',e=>{if(!edit)return;const el=e.target.closest('[contenteditable=true]');if(!el||!el.dataset.ke)return;textMap[el.dataset.ke]=el.innerText;localStorage.setItem(EDIT_KEY,JSON.stringify(textMap))});
  document.addEventListener('click',e=>{if(!edit)return;const media=e.target.closest('.mediaCard img,.mediaCard video,.refCard img,.refCard video,.caseMini img,.caseMini video');if(!media)return;const card=media.closest('[data-a="media"]');let k=logicalKeyFromCard(card);if(!k&&media.closest('.caseMini')){const minis=[...document.querySelectorAll('.caseMini img,.caseMini video')];k=`case-${minis.indexOf(media)}`}if(!k)return;e.preventDefault();e.stopImmediatePropagation();pickFile(k)},true);
  btn.addEventListener('click',()=>{edit=!edit;refresh(); if(edit)openPanel()});
  function pickFile(k){const inp=document.createElement('input');inp.type='file';inp.accept=k==='image-0'?'image/*':'image/*,video/*';inp.onchange=async()=>{const f=inp.files&&inp.files[0];if(!f)return;await dbPut(k,f);showToast('已替换，保存在本机');refresh()};inp.click()}
  function openPanel(){if(!panel){panel=document.createElement('div');panel.className='ke-panel';panel.innerHTML=`<div class="ke-sheet"><div class="ke-head"><h3>编辑 App</h3><button class="ke-close">×</button></div><div class="ke-note">文字：关闭这个面板后，直接点页面上的文字改。素材：在下面选择文件，或在 EDIT 模式下直接点页面里的图片 / 视频替换。修改会保存在这台手机的 Safari 里。</div><div class="ke-grid">${slots.map(s=>`<div class="ke-row"><div><b>${s[1]}</b><small>${s[2]}</small></div><button class="ke-pick" data-slot="${s[0]}">选择文件</button></div>`).join('')}</div><div class="ke-tools"><button id="keExport">导出文字 JSON</button><button id="keImport">导入文字 JSON</button><button id="keMedia">重新打开素材管理</button><button id="keReset" class="danger">清空本机修改</button></div></div>`;document.body.appendChild(panel);panel.querySelector('.ke-close').onclick=()=>panel.classList.remove('show');panel.addEventListener('click',e=>{const p=e.target.closest('[data-slot]');if(p)pickFile(p.dataset.slot)});panel.querySelector('#keExport').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(textMap,null,2)],{type:'application/json'}));a.download='KENZO_text_edits.json';a.click()};panel.querySelector('#keImport').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{textMap=JSON.parse(r.result);localStorage.setItem(EDIT_KEY,JSON.stringify(textMap));showToast('文字已导入');refresh()}catch(e){showToast('JSON 无法读取')}};r.readAsText(f)};i.click()};panel.querySelector('#keMedia').onclick=()=>panel.classList.add('show');panel.querySelector('#keReset').onclick=async()=>{if(!confirm('清空这台手机上的文字和素材修改？'))return;localStorage.removeItem(EDIT_KEY);textMap={};await dbClear();location.reload()}}
    panel.classList.add('show')}
  const obs=new MutationObserver(()=>{clearTimeout(window.__keT);window.__keT=setTimeout(refresh,60)});obs.observe(document.body,{childList:true,subtree:true});
  document.addEventListener('click',async e=>{if(edit)return;const card=e.target.closest('[data-a="media"]');if(!card)return;const k=logicalKeyFromCard(card);if(!k)return;const blob=await dbGet(k).catch(()=>null);if(!blob)return;setTimeout(()=>{const box=document.querySelector('#detail .mediaBox');if(!box)return;box.classList.remove('hide');box.innerHTML='';const isV=blob.type.startsWith('video/');const n=document.createElement(isV?'video':'img');n.className='detailMedia';n.src=URL.createObjectURL(blob);if(isV){n.controls=true;n.autoplay=true;n.loop=true;n.playsInline=true;n.muted=false}box.appendChild(n)},40)});
  setTimeout(refresh,250);
})();